spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_databasse?serverTimezone=GMT
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  devtools:
    restart:
      enabled: true  #设置开启热部署
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  debug: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 1MB
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 1000
    password:
    jedis:
      pool:
        max-active: 8       #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1       #连接池最大阻塞等待时间（使用负值表示没有限制
        max-idle: 8
        min-idle: 0



#  mvc:
#    static-path-pattern: /static/**  配置静态资源的映射

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.demo.pojo  # 注意：对应实体类的路径
# 上传文件总的最大值
server:
  port: 8081
